name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag debianmaster/k3v
<<<<<<< HEAD
    - name: Push docker image
      run: |
        docker ps
=======
>>>>>>> 680634ff07c526649430f07b483c1eee2f1ad007
